### ISSUE TITLE
.NET Standard	support

### ISSUE THREAD

**Issue by seguins** [DocRaptor/docraptor-csharp#16]
The package not working in .NET Standard. 

Do you plan to support it ?

**Comment by JamesPaden** [comment]
It should work in .NET Standard. Do you have an error message or anything?

**Comment by seguins** [comment]
It was long time ago, I don't remember the exact problem, but when I import the Nuget package, I have this warning : 
>Warning	NU1701	Package 'DocRaptor 1.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

Anyway, I directly called your API following [your documentation](https://docraptor.com/documentation/api).
